//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public candidat()
        {
            this.offres = new HashSet<offre>();
        }
    
        public long Identifiant { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Portable { get; set; }
        public string Rue { get; set; }
        public int CP { get; set; }
        public string Ville { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string Permis { get; set; }
        public long IdentifiantCompte { get; set; }
    
        public virtual compte compte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<offre> offres { get; set; }
    }
}
