//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMegaCasting.DBLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class megacastingv2Entities : DbContext
    {
        public megacastingv2Entities()
            : base("name=megacastingv2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<candidat> candidats { get; set; }
        public virtual DbSet<compte> comptes { get; set; }
        public virtual DbSet<contrat> contrats { get; set; }
        public virtual DbSet<domaine> domaines { get; set; }
        public virtual DbSet<metier> metiers { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<offre> offres { get; set; }
    }
}
