//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionMegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public offre()
        {
            this.candidats = new HashSet<candidat>();
        }
    
        public long Identifiant { get; set; }
        public string Libelle { get; set; }
        public string Reference { get; set; }
        public System.DateTime DateDebutPublication { get; set; }
        public System.DateTime DateFinPublication { get; set; }
        public System.DateTime DateDebutContrat { get; set; }
        public System.DateTime DateFinContrat { get; set; }
        public string DescriptionPoste { get; set; }
        public string DescriptionProfil { get; set; }
        public Nullable<int> NombresPoste { get; set; }
        public long IdentifiantClient { get; set; }
        public long IdentifiantMetier { get; set; }
        public long IdentifiantContrat { get; set; }
    
        public virtual client client { get; set; }
        public virtual contrat contrat { get; set; }
        public virtual metier metier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidat> candidats { get; set; }
    }
}
